language: python
sudo: required
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest
  - poetry run flake8
services:
  - postgresql
env:
  - PGUSER=postgres
